MODULE=custom_driver

obj-m += ${MODULE}.o
#${MODULE}-objs :=custom_driver.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
